name: ws2024-crs
channels:
  - defaults
dependencies:
  - pandas
  - pyproj >= 3.6.0
  - python >= 3.9
  - cartopy
  - geopandas >= 0.12.0
  - matplotlib
  - owslib
  - ipyleaflet
  - planetary-coverage
  - pyvista 
  - pykdtree
